import Image from "next/image";
import Link from "next/link";
import { SITE } from "@/shared/config/site";
import { LightboxGallery } from "@/shared/ui/lightbox-gallery";
const benefits=[["Питательные компоненты",["Белки и пептиды","Полисахариды и тритерпеновые гликозиды","Фосфолипиды и другие липидные соединения"]],["Минеральный состав",["В научных работах исследуются кальций, магний, железо и цинк","Состав зависит от места добычи, сезона и способа обработки","Точные значения для продукта следует смотреть на его маркировке"]],["Почему важна обработка",["Нагрев, сушка и другие процессы меняют влажность и концентрацию веществ","Щадящая технология помогает работать с чувствительными компонентами сырья","Состав готового продукта нельзя приравнивать к составу свежего трепанга"]]] as const;
function About(){const documents=[1,2,3,4,5].map(number=>`/images/docs/doc${number}.webp`);return <><p>Компания <b>«Доктор Панг»</b> ИП Вороной С.В. разработала собственную технологию приготовления ферментативного гидролизата трепанга в капсулах с использованием вакуумной сушки. Такой способ исключает интенсивную термическую обработку и помогает сохранить природный состав сырья.</p><p>Мы предлагаем продукцию собственного производства из морских биоресурсов Дальнего Востока. Продукция имеет разрешительную документацию для реализации через аптечные сети и интернет-магазины.</p><p>Продукт не является лекарственным средством. Перед применением рекомендуется ознакомиться с информацией изготовителя и проконсультироваться со специалистом.</p><h2 className="pt-6 text-3xl font-extrabold">Документы</h2><LightboxGallery images={documents} name="Разрешительные документы" variant="documents"/></>}
function Trepang(){return <>
  <p className="text-xl leading-9">Дальневосточный трепанг — морское донное животное, известное также как японский морской огурец. Его современное научное название — <i>Apostichopus japonicus</i>. Несмотря на бытовое слово «моллюск», трепанг относится не к моллюскам, а к типу иглокожих и классу голотурий.</p>
  <div className="grid gap-4 pt-3 sm:grid-cols-3"><div className="rounded-3xl bg-[#17352d] p-6 text-white"><b className="text-2xl">Иглокожее</b><p className="mt-2 text-sm text-white/70">Родственник морских звёзд и ежей</p></div><div className="rounded-3xl bg-[#dfeee7] p-6"><b className="text-2xl">Донный вид</b><p className="mt-2 text-sm text-black/55">Живёт на морском дне и собирает органические частицы</p></div><div className="rounded-3xl bg-[#f5f0e6] p-6"><b className="text-2xl">Северная Пацифика</b><p className="mt-2 text-sm text-black/55">Распространён у берегов северной части Тихого океана</p></div></div>
  <h2 className="pt-7 text-3xl font-extrabold">Как живёт трепанг</h2>
  <p>Трепанг передвигается по грунту и питается органическими частицами, которые собирает донными щупальцами. Тем самым голотурии участвуют в переработке донных отложений и круговороте веществ морской экосистемы. Для <i>Apostichopus japonicus</i> характерна сезонная активность: температура воды влияет на питание, рост и периоды покоя.</p>
  <p>Вид встречается у побережий России, Японии, Кореи и Китая. Окраска и внешний вид могут отличаться в зависимости от среды обитания. В пищевой культуре стран Восточной Азии морские огурцы используются давно, а сегодня их состав исследуют как сырьё для пищевых и функциональных продуктов.</p>
  <h2 className="pt-7 text-3xl font-extrabold">Что содержится в трепанге</h2>
  <p>Исследования <i>Apostichopus japonicus</i> описывают белки и пептиды, полисахариды, сапонины, липиды, аминокислоты и минеральные вещества. Однако конкретное количество компонентов зависит от происхождения сырья и технологии приготовления. Поэтому показатели свежего трепанга нельзя автоматически переносить на сушёный продукт, экстракт или капсулы.</p>
  <div className="grid gap-4 pt-4 md:grid-cols-3">{benefits.map(([title,items])=><section className="rounded-3xl bg-[#dfeee7] p-6" key={title}><h3 className="text-xl font-extrabold">{title}</h3><ul className="mt-4 grid gap-3 text-sm leading-6">{items.map(item=><li className="flex gap-2" key={item}><span aria-hidden="true" className="text-[#df7457]">●</span>{item}</li>)}</ul></section>)}</div>
  <h2 className="pt-7 text-3xl font-extrabold">Ферментативный гидролизат</h2>
  <p>При гидролизе белковые компоненты сырья расщепляются на более короткие фрагменты — пептиды и аминокислоты. «Доктор Панг» использует собственную технологию получения гидролизата и вакуумную сушку без интенсивной термической обработки. Готовый материал выпускается в капсулах; точный состав, масса, количество капсул и рекомендации по применению указываются на этикетке конкретного товара.</p>
  <h2 className="pt-7 text-3xl font-extrabold">В каком виде выпускают продукты</h2>
  <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-black/10 p-6"><h3 className="text-xl font-extrabold">На меду</h3><p className="mt-2 text-sm">Трепанг в пищевой основе. Состав и условия хранения смотрите на упаковке.</p></div><div className="rounded-3xl border border-black/10 p-6"><h3 className="text-xl font-extrabold">В капсулах</h3><p className="mt-2 text-sm">Компактная форма гидролизата или экстракта с указанной производителем порцией.</p></div><div className="rounded-3xl border border-black/10 p-6"><h3 className="text-xl font-extrabold">Сушёный</h3><p className="mt-2 text-sm">Продукт с удалённой влагой, требующий соблюдения способа приготовления.</p></div></div>
  <div className="grid gap-4 pt-3 sm:grid-cols-2"><aside className="rounded-3xl bg-emerald-50 p-6"><h3 className="text-xl font-extrabold text-emerald-800">Как выбирать</h3><p className="mt-3 text-sm">Проверяйте состав, срок годности, условия хранения, данные изготовителя и сведения о государственной регистрации БАД. Следуйте маркировке конкретного продукта.</p></aside><aside className="rounded-3xl bg-red-50 p-6"><h3 className="text-xl font-extrabold text-red-800">Важно</h3><p className="mt-3 text-sm">БАД не является лекарством и не предназначена для лечения заболеваний. При беременности, грудном вскармливании, хронических заболеваниях, приёме лекарств или аллергии на морепродукты проконсультируйтесь с врачом.</p></aside></div>
  <section className="mt-3 rounded-3xl bg-[#f5f0e6] p-6"><h2 className="text-2xl font-extrabold">Источники и дополнительная информация</h2><ul className="mt-4 grid gap-2 text-sm"><li><a className="underline underline-offset-4" href="https://www.ncbi.nlm.nih.gov/datasets/taxonomy/307972/" target="_blank" rel="noreferrer">NCBI: систематика Apostichopus japonicus</a></li><li><a className="underline underline-offset-4" href="https://pubmed.ncbi.nlm.nih.gov/37853667/" target="_blank" rel="noreferrer">Обзор химического состава Apostichopus japonicus</a></li><li><a className="underline underline-offset-4" href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6393041/" target="_blank" rel="noreferrer">Исследование влияния обработки на пищевой состав</a></li><li><a className="underline underline-offset-4" href="https://pda.04.rospotrebnadzor.ru/index.php/consumer-information/faq/19854-05022025.html" target="_blank" rel="noreferrer">Роспотребнадзор: памятка потребителю о БАД</a></li></ul></section>
  <p className="text-sm text-black/45">Информация носит справочный характер. Биологически активная добавка к пище не является лекарственным средством.</p>
</>}
function Delivery(){return <><p>Мы отправляем продукцию по всей территории России и в страны СНГ.</p><h2 className="pt-4 text-3xl font-extrabold">Способы получения</h2><ul className="grid gap-4 md:grid-cols-3"><li className="rounded-3xl bg-[#dfeee7] p-6"><b>Почта России</b><p className="mt-2 text-sm">После 100% предоплаты, стоимость — по тарифу перевозчика.</p></li><li className="rounded-3xl bg-[#dfeee7] p-6"><b>EMS</b><p className="mt-2 text-sm">Курьерская доставка по России и за границу после предоплаты.</p></li><li className="rounded-3xl bg-[#dfeee7] p-6"><b>Самовывоз</b><p className="mt-2 text-sm">Во Владивостоке по звонку: +7 (902) 055-55-52.</p></li></ul><p><b>Обратите внимание:</b> отправка в регионы осуществляется после полной оплаты. Индивидуальная упаковка оплачивается отдельно — 155 рублей. Продукт защищается плёнкой и помещается в картонную коробку.</p><p>Оплата возможна наличным и безналичным способом.</p><Image src="/images/shipping.png" alt="Доставка продукции" width={1000} height={500} className="h-auto w-full rounded-3xl"/></>}
const headings={about:"О компании",trepang:"Что такое трепанг?",delivery:"Доставка по России и СНГ"} as const;
const paths={about:"/about",trepang:"/trepang",delivery:"/delivery"} as const;
export function ContentPage({kind}:{kind:keyof typeof headings}){const breadcrumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Главная",item:SITE.url},{"@type":"ListItem",position:2,name:headings[kind],item:`${SITE.url}${paths[kind]}`}]};return <main className="container-page py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbs).replace(/</g,"\\u003c")}}/><article className="rounded-[36px] bg-white p-8 shadow-sm md:p-14"><nav aria-label="Хлебные крошки" className="mb-7 flex items-center gap-2 text-sm text-black/45"><Link href="/" className="hover:text-[#df7457]">Главная</Link><span aria-hidden="true">/</span><span aria-current="page">{headings[kind]}</span></nav><p className="font-bold uppercase tracking-[.16em] text-[#df7457]">Доктор Панг</p><h1 className="mt-3 text-5xl font-extrabold">{headings[kind]}</h1><div className="mt-8 grid gap-5 text-lg leading-8 text-black/65">{kind==="about"?<About/>:kind==="trepang"?<Trepang/>:<Delivery/>}</div></article></main>}
