"use server";
import { mkdir,writeFile } from "node:fs/promises"; import path from "node:path"; import { randomUUID } from "node:crypto"; import { redirect } from "next/navigation"; import { revalidatePath } from "next/cache"; import { z } from "zod"; import { clearAdminSession,createAdminSession,requireAdmin,validPassword } from "@/shared/auth"; import { deleteProduct,getProductById,markCustomerRequest,saveProduct } from "@/shared/db";
export async function loginAction(form:FormData){if(!validPassword(String(form.get("password")||"")))redirect("/admin/login?error=1");await createAdminSession();redirect("/admin")}
export async function logoutAction(){await clearAdminSession();redirect("/admin/login")}
const schema=z.object({name:z.string().trim().min(2),slug:z.string().trim().regex(/^[a-z0-9-]+$/),shortDescription:z.string(),description:z.string(),price:z.coerce.number().int().nonnegative(),discount:z.coerce.number().int().min(0).max(100),ozonUrl:z.string(),wbUrl:z.string(),sortOrder:z.coerce.number().int(),active:z.boolean()});
async function uploads(files:File[]){const dir=path.join(process.cwd(),"public","uploads");await mkdir(dir,{recursive:true});const result:string[]=[];for(const file of files){if(!file.size)continue;if(file.size>8*1024*1024||!file.type.startsWith("image/"))throw new Error("Допустимы изображения до 8 МБ");const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const name=`${randomUUID()}.${ext}`;await writeFile(path.join(dir,name),Buffer.from(await file.arrayBuffer()));result.push(`/uploads/${name}`)}return result}
export async function saveProductAction(id:number|undefined,form:FormData){await requireAdmin();const parsed=schema.parse({name:form.get("name"),slug:form.get("slug"),shortDescription:String(form.get("shortDescription")||""),description:String(form.get("description")||""),price:form.get("price"),discount:form.get("discount"),ozonUrl:String(form.get("ozonUrl")||""),wbUrl:String(form.get("wbUrl")||""),sortOrder:form.get("sortOrder"),active:form.get("active")==="on"});const old=id?getProductById(id):null;const keep=old?.images.filter(x=>form.getAll("removeImage").includes(x)===false)||[];const images=[...keep,...await uploads(form.getAll("images").filter((x):x is File=>x instanceof File))];saveProduct({...parsed,images},id);revalidatePath("/");revalidatePath("/admin");redirect("/admin")}
export async function deleteProductAction(id:number){await requireAdmin();deleteProduct(id);revalidatePath("/");revalidatePath("/admin")}
export async function toggleRequestAction(id:number,processed:boolean){await requireAdmin();markCustomerRequest(id,processed);revalidatePath("/admin")}
